import POO.DOMINIO.*;

public class App {
    public static void main(String[] args) throws Exception {
        Carro c1 = new Carro(679810472, 
        "Campo Grande", 
        "Mato Grosso do Sul", 
        "Fiat Bravo", 
        "Essence", 
        "vermelho", 
        2013, 
        2012, 
        5, 
        4, 
        "Fiat", 
        142d, 
        "Gasolina", 
        "Marcos Castro",
         "Carro", 
         1, 
         2, 
         "593495", 
         "HHR - 9516", 
         "4718924", 
         "Manual",
            2,
          "Hatch", 
          4 );

          c1.imprimir();

          Aviao a1 = new Aviao(336545213, 
          "Belo Horizonte", 
          "Minas Gerais", 
          "Airbus A320", 
          "A320 neo", 
          "Branco", 
          2015, 
          2014, 
          220, 
          10, 
          "Airbus", 
          25000d, 
          "Querosene", 
          "Gol", 
          "Avião", 
          2, 
          205, 
          2, 
          "AB - JDC", 
          50000d);
          
          a1.imprimir();

          Motocicleta m1 = new Motocicleta(667831245, 
          "Campinas", 
          "São Paulo", 
          "Honda CG 150", 
          "Titan", 
          "Vermelho", 
          2015, 
          2014, 
          2, 
          2, 
          "Honda", 
          15d, 
          "Gasolina", 
          "Jonathan da Silva", 
          "Motocicleta", 
          1, 
          1, 
          "936457", 
          "NRI - 9926", 
          "3184578", 
          "Manual",
          1, 
          150);

          m1.imprimir();

          Caminhao c2 = new Caminhao(874397545, 
          "Porto Velho", 
          "Rondônia", 
          "Volvo FH 540", 
          "EURO6", 
          "Branco", 
          2017, 
          2016, 
          2, 
          6, 
          "Volvo", 
          540d, 
          "Diesel", 
          "Marcos do Val", 
          "Caminhão", 
          1, 
          1, 
          "349065", 
          "HMI - 4356", 
          "1904385", 
          "Manual", 
          1046d, 
          6200d, 
          3, 
          2);
          c2.imprimir();

          Onibus o1 = new Onibus(859435468, 
          "Goiania", 
          "Goiás", 
          "Marcopolo Torino", 
          "G8", 
          "Vermelho", 
          2014, 
          2013, 
          45, 
          4, 
          "Marcopolo", 
          400d, "Gasolina", 
          "Guaicurus", 
          "Ônibus", 
          1, 
          36, 
          "589456", 
          "MRP - 9012", 
          "8905654", 
          "Manual", 
          2,
          6);
          o1.imprimir();


    }
}
